---
title: "STT1810 Spring 2018"
author: "Instructor: Dr. Jill E. Thomley"
date: "Updated: `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

```{r echo=F}
# themes: “default”, “cerulean”, “journal”, “flatly”, “readable”, “spacelab”, “united”, “cosmo”, “lumen”, “paper”, “sandstone”, “simplex”, “yeti”  UNITED
```

<hr>

### Welcome!

This is a preliminary schedule for the course up through Spring Break. Face to face meetings are on Tuesdays and Thursdays. Online homework and quizzes in Webassign are due Mondays (MON), Wednesdays (WED) and Fridays (FRI). Changes to this schedule will be announced, but also pay attention to the "updated" date above. More weeks will be added as we go along. 



### Week 01

#### Tuesday, January 16

   In Class:
   
   * Introduction to STT1810
   * Most Developed Country data collection

   Before Next Class: 
   
   * Read Utts & Heckard Chapter 01
   * Read Utts & Heckard Sections 7.1 to 7.4
   * Watch "Introduction & Statistical Thinking"
   * Watch "Probability: The Basics and Example"
   * Watch "Two-Way Tables and Venn Diagrams"

#### Thursday, January 18

   In Class:
   
   * Random circumstances
   * Relative frequency
   * Frequency tables
   * Contingency tables
   * Probability rules!

   Before Next Class: 
   
   * Read Utts & Heckard Sections 7.5 to 7.7
   * Watch "Conditional Probability"
   * Watch "Conditional Probability and Independence"
   * Watch "Conditional Probability Tree Diagram Example"
   * Webassign "CH01--Introduction and Case Studies" (FRI)
   * Webassign "CH07--7.1 Randomness and 7.2 Interpretatations" (MON)



### Week 02

#### Tuesday, January 23

   In Class:
   
   * Conditional probability
   * Tables and tree diagrams
   * Sensitivity and specificity

   Before Next Class: 
   
   * Webassign "CH07--7.3 Definitions and 7.4 Probability Rules" (WED)
   
#### Thursday, January 25

   In Class:
   
   * Conditional probability
   * Tables and tree diagrams
   * Sensitivity and specificityy
   * MBTI data collection activity

   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.1 to 2.3
   * Watch "Scales of Measurement, Part 1"
   * Watch "Scales of Measurement, Part 2"
   * Webassign "CH07--7.5 Conditional Prob and 7.7 Flawed Judgment" (FRI)
   * Webassign "CH07 QUIZ" (MON)

   
   
### Week 03

#### Tuesday, January 30

   In Class:
   
   * Language of data/variables
   * Tables for categorical data
   * Graphs for categorical data

   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.4 to 2.5
   * Watch "Frequency Tables and Dotplots"
   * Watch "Stem and Leaf Plots"
   * Watch "Creating a Histogram"
   * Watch "Interpreting a Histogram"
   * Webassign "CH02--2.1 Raw Data and 2.2 Types of Variables" (WED)
   
#### Thursday, February 01

   In Class:
   
   * Language of data/variables
   * Graphs for quantitative data
   * Summaries for quantitative data

   Before Next Class: 
   
   * Read Utts & Heckard Section 2.6
   * Watch "Mean and Median: The Basics"
   * Watch "Stats Intro: Mean, Median, and Mode"
   * Watch "Variance of a Population"
   * Watch "Population Standard Deviation"
   * Watch "Sample Variance"
   * Watch "Sample Standard Deviation"
   * Webassign "CH02--2.3 Summarizing Categorical Variables" (FRI)
   * Webassign "CH02--2.4 Graphs of Quantitatative Variables" (MON)

   

### Week 04

#### Tuesday, February 06

   In Class:
   
   * Boxplots for quantitative data
   * Finding outliers using boxplots

   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.7
   * Watch "Percentiles"
   * Watch "Introduction to the Normal Distribution"
   * Watch "Comparing With Z-Scores"
   * Webassign "CH02--2.5a Means, Medians, Modes" (WED)
   
#### Thursday, February 08

   In Class:
   
   * Standardized Scores
   * Bell-Shaped Distributions
   * Normal Probability Plots

   Before Next Class: 
   
   * Read Utts & Heckard Sections 3.1-3.2
   * watch "Bivariate Linearity, Relationship, and Strength"
   * Watch "Introduction to Simple Linear Regression"
   * Watch "Simple Linear Regression: Interpreting the Parameters"
   * Webassign "CH02--2.5b Five-Number Summaries, Boxplots, %-iles" (FRI)
   * Webassign "CH02--2.7a Standard Deviations" (MON)

   
   
### Week 05

#### Tuesday, February 13

   In Class:
   
   * Anthropometric data collection
   * Scatterplots for bivariate data
   * Least squares regression lines

   Before Next Class: 
   
   * Watch "Introduction to Residuals"
   * Watch "Calculating Residual Example"
   * Watch "R Squared or Coefficient of Determination"
   * Webassign "CH02--2.7b Bell-Shaped Distributions" (WED)
   
#### Thursday, February 15

   In Class:
   
   * Least squares regression lines
   * Interpreting coefficients
   * Making predictions

   Before Next Class: 
   
   * Read Utts & Heckard Sections 3.3-3.5
   * Watch "Calculating Correlation Coefficient r"
   * Webassign "CH02--2.7c Standard Normal Curve and Z-Scores" (FRI)
   * Webassign "CH02 QUIZ" (MON)


   
### Week 06

#### Tuesday, February 20

   In Class:
   
   * Correlation coefficients
   * Difficulties and disasters

   Before Next Class: 
   
   * Webassign "CH03--3.1 Scatterplots and 3.2 Regression Line" (WED)
   
#### Thursday, February 22

   In Class:
   
   * Two-way tables and plots
   * Risk, relative risk, and increased risk

   Before Next Class: 

   * Webassign "CH03--3.3 Correlation and 3.4 Difficulties" (FRI)
   * Webassign "CH03 QUIZ" (MON)

   
   
### Week 07

#### Tuesday, February 27

   In Class:
   
   * Odds and odds ratios

   Before Next Class: 
   
   * Complete take-home portion of EXAM 01 (WED)

<hr>   
   
#### Thursday, March 01

   In Class:
   
   * In-class portion of EXAM 01

   Before Next Class: 
   
   * Read Utts & Heckard Sections 4.3-4.4

<hr>



### Spring Break!

<hr>



### Final Exam

The final exam is on Tuesday, May 06 @ 2pm.
