---
title: "STT1810 Spring 2018"
author: "Instructor: Dr. Jill E. Thomley"
date: "Updated: `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

```{r echo=F}
# themes: “default”, “cerulean”, “journal”, “flatly”, “readable”, “spacelab”, “united”, “cosmo”, “lumen”, “paper”, “sandstone”, “simplex”, “yeti”  UNITED
```

<hr>

### Welcome!

<strike>This is a preliminary schedule for the course up through Spring Break. More weeks will be added as we go along.</strike> This schedule covers the entire semester, but assignments may still be added. Face to face meetings are on Tuesdays and Thursdays. Online homework and quizzes in Webassign are due Mondays (MON), Wednesdays (WED) and Fridays (FRI). Changes to this schedule will be announced, but also pay attention to the "updated" date above.  



### Week 01

#### **Tuesday, January 16**

   In Class:
   
   * Introduction to STT1810
   * Most Developed Country data collection

   Before Next Class: 
   
   * Read Utts & Heckard Chapter 01
   * Read Utts & Heckard Sections 7.1 to 7.4
   * Watch "Introduction & Statistical Thinking"
   * Watch "Probability: The Basics and Example"
   * Watch "Two-Way Tables and Venn Diagrams"

#### **Thursday, January 18**

   In Class:
   
   * Random circumstances
   * Relative frequency
   * Frequency tables
   * Contingency tables
   * Probability rules!

   Before Next Class: 
   
   * Read Utts & Heckard Sections 7.5 to 7.7
   * Watch "Conditional Probability"
   * Watch "Conditional Probability and Independence"
   * Watch "Conditional Probability Tree Diagram Example"
   * Webassign "CH01--Introduction and Case Studies" (FRI Jan-19)
   * Webassign "CH07--7.1 Randomness and 7.2 Interpretatations" (MON Jan-22)



### Week 02

#### **Tuesday, January 23**

   In Class:
   
   * Conditional probability
   * Tables and tree diagrams
   * Sensitivity and specificity

   Before Next Class: 
   
   * Webassign "CH07--7.3 Definitions and 7.4 Probability Rules" (WED Jan-24)
   
#### **Thursday, January 25**

   In Class:
   
   * Conditional probability
   * Tables and tree diagrams
   * Sensitivity and specificityy
   * MBTI data collection activity

   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.1 to 2.3
   * Watch "Scales of Measurement, Part 1"
   * Watch "Scales of Measurement, Part 2"
   * Webassign "CH07--7.5 Conditional Prob and 7.7 Flawed Judgment" (FRI Jan-26)
   * Webassign "CH07 QUIZ" (MON Jan-29)

   
   
### Week 03

#### **Tuesday, January 30**

   In Class:
   
   * Language of data/variables
   * Tables for categorical data
   * Graphs for categorical data

   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.4 to 2.5
   * Watch "Frequency Tables and Dotplots"
   * Watch "Stem and Leaf Plots"
   * Watch "Creating a Histogram"
   * Watch "Interpreting a Histogram"
   * Webassign "CH02--2.1 Raw Data and 2.2 Types of Variables" (WED Jan-31)
   
#### **Thursday, February 01**

<strike>In Class:
   
   * Language of data/variables
   * Graphs for quantitative data
   * Summaries for quantitative data

   Before Next Class: 
   
   * Read Utts & Heckard Section 2.6
   * Watch "Mean and Median: The Basics"
   * Watch "Stats Intro: Mean, Median, and Mode"
   * Watch "Variance of a Population"
   * Watch "Population Standard Deviation"
   * Watch "Sample Variance"
   * Watch "Sample Standard Deviation"
   * Webassign "CH02--2.3 Summarizing Categorical Variables"</strike>

<span style="color:red">This face to face class meeting was canceled due to illness.</span>
   
   

### Week 04

#### **Tuesday, February 06**

   In Class:

   * Language of data/variables
   * Graphs for quantitative data
   * Summaries for quantitative data

   Before Next Class: 
   
   * Read Utts & Heckard Section 2.6
   * Watch "Mean and Median: The Basics"
   * Watch "Stats Intro: Mean, Median, and Mode"
   * Watch "Percentiles"
   * Webassign "CH02--2.3 Summarizing Categorical Variables"

#### **Thursday, February 08**

   In Class:

   * Summaries for quantitative data   
   * Boxplots for quantitative data
   * Finding outliers using boxplots
   
   Before Next Class: 
   
   * Read Utts & Heckard Sections 2.7
   * Watch "Variance of a Population"
   * Watch "Population Standard Deviation"
   * Watch "Sample Variance"
   * Watch "Sample Standard Deviation"
   * Watch "Introduction to the Normal Distribution"
   * Watch "Comparing With Z-Scores"
   * Webassign "CH02--2.4 Graphs of Quantitatative Variables" (FRI Feb-09)
   * Webassign "CH02--2.5a Means, Medians, Modes" (FRI Feb-09)
   * Webassign "CH02--2.5b Five-Number Summaries, Boxplots, %-iles" (MON Feb-12)

   
   
### Week 05

#### **Tuesday, February 13**

   In Class:

   * Standard Deviation/Variance
   * Bell-Shaped Distributions
   * Standardized Scores

   Before Next Class: 

   * Make sure to complete all reading and video assignments
   * Webassign "CH02--2.7a Standard Deviations" (WED Feb-14)

#### **Thursday, February 15**

   In Class:
   
   * "Putting it All Together" Activities
   
   Before Next Class: 
   
   * Read Utts & Heckard Sections 3.1-3.2
   * Watch "Bivariate Linearity, Relationship, and Strength"
   * Watch "Introduction to Simple Linear Regression"
   * Webassign "CH02--2.7b Bell-Shaped Distributions" (FRI Feb-16)
   * Webassign "CH02--2.7c Standard Normal Curve and Z-Scores" MON Feb-19)  
   

   
### Week 06

#### **Tuesday, February 20**

   In Class:
   
   * Anthropometric data collection
   * Scatterplots for bivariate data
   * Least squares regression models

   Before Next Class: 

   * Watch "Simple Linear Regression: Interpreting the Parameters"
   * Watch "Introduction to Residuals"
   * Watch "Calculating Residual Example"
   * Webassign "CH02 QUIZ" (WED Feb-21)

#### **Thursday, February 22**

   In Class:

   * Interpreting the model coefficients
   * Using the model to make predictions
   * Calculating residuals for the model

   Before Next Class: 

   * TAKE-HOME PORTION OF EXAM 1 DUE (MON Feb-26)
   

   
### Week 07

#### **Tuesday, February 27**

   In Class:
   
   * IN-CLASS PORTION OF EXAM 01
   * Covers Chapters 1, 2, and 7

   Before Next Class: 
   
   * Read Utts & Heckard Sections 3.3-3.5
   * Watch "Calculating Correlation Coefficient r"
   * Watch "R Squared or Coefficient of Determination"

#### **Thursday, March 01**

   In Class:
   
   * Pearson correlation coefficient (r)
   * Coefficient of Determination (R<sup>2</sup>)
   * Difficulties and disasters

   Before Next Class: 
   
   * Read Utts & Heckard Sections 4.1-4.2
   * Webassign "CH03--3.1 Scatterplots and 3.2 Regression Line" FRI Mar-02)
   
<hr>



### Spring Break!

<hr>



### Week 08

#### **Tuesday, March 13**

   In Class:
   
   * Two-way tables and plots
   * Risk, relative risk, % increased risk 

   Before Next Class: 

   * Read Utts & Heckard Section 4.3   
   * Webassign "CH03--3.3 Correlation and 3.4 Difficulties" (WED Mar-14)


#### **Thursday, March 15**

   In Class:
   
   * Risk, Relative Risk, % Increased Risk
   * Odds and Odds Ratios
   * Simpson's Paradox

   Before Next Class: 

   * Read Utts & Heckard Section 4.4 
   * Watch "Introduction to the Chi-Square Distribution"
   * Watch "An Introduction to Hypothesis Testing"
   * Watch "What is a P-Value?"
   * Watch "Type I Errors, Type II Errors, and the Power of the Test"
   * Watch "Statistical Significance versus Practical Significance"
   * Watch "Chi-Square Tests for Two-Way Tables"
   * Webassign "CH03 QUIZ" (FRI Mar-16)



### Week 09

#### **Tuesday, March 20**

   In Class:
   
   * Logic of Hypothesis Testing
   * Chi-Square Test of Independence

   Before Next Class: 
   
   * Read Utts & Heckard Sections 4.4
   * Webassign "CH03 QUIZ" (FRI Mar-16)

#### **Thursday, March 22**

   In Class:
   
   * Chi-Square Test of Independence

   Before Next Class: 

   * Make sure to complete all reading and video assignments   
   * Webassign "CH04--4.1 Categorical Relationships and 4.2 Risks" (MON Mar-19)



### Week 10

#### **Tuesday, March 27**

   In Class:
   
   * "Putting it All Together" Activities

   Before Next Class: 
   
   * Read Utts & Heckard Sections 5.1, 5.3-5.4

#### **Thursday, March 29**

   In Class:

   * Survey Basics 
   * Survey Biases
   * Sampling Methods

   Before Next Class: 
   
   * Read Utts & Heckard Sections 5.5-5.6



### Week 11

#### **Tuesday, April 03**

   In Class:
   
   * State Holiday, no face to face meeting today.

   Before Next Class: 
   
   * Catch up on any work on which you are behind.

#### **Thursday, April 05**

   In Class:

   * Difficulties and Disasters
   * Analyzing Gallup Polls

   Before Next Class: 
   
   * TAKE-HOME PORTION OF EXAM 2 DUE (MON Apr-09)



### Week 12

#### **Tuesday, April 10**

   In Class:
   
   * IN-CLASS PORTION OF EXAM 2
   * Covers Chapters 3 and 4

   Before Next Class: 
   
   * Read Utts & Heckard Sections 5.2

#### **Thursday, April 12**

   In Class:

   * Confidence Intervals

   Before Next Class: 
   
   * Webassign "CH05--5.1 Sample Data, 5.3 SRS, and 5.4 Other Samples" (FRI Apr-13)



### Week 13

#### **Tuesday, April 17**

   In Class:
   
   * Confidence Intervals
  
   Before Next Class: 
   
   * Read Utts & Heckard Sections 6.1-6.2

#### **Thursday, April 19**

   In Class:

   * Language of Research Studies
   * Determining Cause and Effect
   * Observational vs. Experimental
   * Designing a Good Experiment

   Before Next Class: 

   * Read Utts & Heckard Sections 6.3-6.4
   * Webassign "CH05--5.2 Margin of Error and Confidence Intervals" (FRI Apr-20)
   * Webassign "CH05 QUIZ" (MON Apr-23)



### Week 14

#### **Tuesday, April 24**

   In Class:

   * Designing a Good Experiment
   * Designing a Good Observational Study
   * Research Difficulties and Disasters
  
   Before Next Class: 
   
   * Assignment TBA

#### **Thursday, April 26**

   In Class:

   * Analyzing Published Studies

   Before Next Class: 
   
   * Webassign "CH06--6.1 Research Language and 6.4 Difficulties" (FRI Apr-27)
   * Webassign "CH06--6.2 Experimental and 6.3 Observational" (MON Apr-30)
   * Make sure to complete all reading and video assignments
   


### Week 15

#### **Tuesday, April 24**

   In Class:
   
   * "Putting it All Together" Activities
  
   Before Next Class: 
   
   * Webassign "CH06 QUIZ" (WED May-02)

#### **Thursday, April 26**

   Today is Reading Day! Look for office hour announcements.



### Final Exam

The FINAL EXAM is on Tuesday, May 06 @ 2pm in WA 307B. The exam covers Chapters 5 and 6.
